# Generated by Django 4.2.2 on 2024-07-05 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('RT', 'Retiro en Tienda'), ('DD', 'Despacho a Domicilio')], default='RT', max_length=2)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_pedido', models.CharField(max_length=10, unique=True)),
                ('datos_completados', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('detalleCompleto', models.TextField(default='')),
                ('especificaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('lista1', models.CharField(blank=True, max_length=100, null=True)),
                ('lista2', models.CharField(blank=True, max_length=100, null=True)),
                ('lista3', models.CharField(blank=True, max_length=100, null=True)),
                ('lista4', models.CharField(blank=True, max_length=100, null=True)),
                ('lista5', models.CharField(blank=True, max_length=100, null=True)),
                ('incluye', models.CharField(blank=True, max_length=100, null=True)),
                ('lista6', models.CharField(blank=True, max_length=100, null=True)),
                ('lista7', models.CharField(blank=True, max_length=100, null=True)),
                ('lista8', models.CharField(blank=True, max_length=100, null=True)),
                ('lista9', models.CharField(blank=True, max_length=100, null=True)),
                ('lista10', models.CharField(blank=True, max_length=100, null=True)),
                ('precioOferta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('buy_order', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('authorization_code', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type_code', models.CharField(blank=True, max_length=50, null=True)),
                ('response_code', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremas_APP.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremas_APP.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremas_APP.producto')),
            ],
        ),
    ]
