# Generated by Django 5.0.5 on 2024-05-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas_APP', '0004_producto_descripcionlarga_producto_detallecompleto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcionLarga',
            new_name='especificaciones',
        ),
        migrations.AddField(
            model_name='producto',
            name='incluye',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='lista1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='lista10',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='lista2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='lista3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='lista4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='lista5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='lista6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='lista7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='lista8',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='lista9',
            field=models.TextField(default=''),
        ),
    ]
