# Generated by Django 4.2.2 on 2024-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas_APP', '0006_alter_producto_especificaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('RT', 'Retiro en Tienda'), ('DD', 'Despacho a Domicilio')], default='RT', max_length=2)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_pedido', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
