# Generated by Django 4.2.2 on 2024-06-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremas_APP', '0009_pedido_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='datos_completados',
            field=models.BooleanField(default=False),
        ),
    ]
